### ISSUE TITLE
commands don't resolve aliases

### ISSUE THREAD

**Issue by rsgalloway** [rsgalloway/envstack#1]
when running commands using `--` aliases are not resolved, e.g.

```bash
$ envstack -- <command>
```
where `<command>` is an alias results in a FileNotFoundError:

```bash
$ alias foo=ls
$ envstack -- foo
Traceback (most recent call last):
...
    process = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'foo'

```

**Comment by rsgalloway** [comment]
solution may involve invoking the original shell:

```python
# Use bash with the '-i' option to start an interactive shell,
# which loads aliases and functions defined in .bashrc or .zshrc
command = "your_alias_command"  # Replace with the alias or command you want to run
process = subprocess.Popen(
    ['bash', '-i', '-c', command],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE
)
```

**Comment by rsgalloway** [comment]
another consideration: defining aliases in .env files that can be exported to bash (or any shell), e.g defining an alias to an executable called `run` with predefined cli args:

```yaml
alias:
  run: "${DEPLOY_ROOT}/bin/run --a=1 --b=2"
```

This would have to be exported and sourced in the shell:

```bash
$ envstack --export
...
export DEPLOY_ROOT="${ROOT}/${ENV}"
alias run="${DEPLOY_ROOT}/bin/run --a=1 --b=2"
$ source <(envstack --export)
```

It would be convenient if it could be run as a command like this:

```bash
$ envstack -- run
```

**Comment by rsgalloway** [comment]
aliases defined in the env stack file could get exported as part of the `envstack-init` function defined [here](https://github.com/rsgalloway/envstack?tab=readme-ov-file#shells):

```bash
alias envstack-set='source <(envstack "$1" --export)';
envstack-init() { envstack-clear "$1"; envstack-set "$1"; }
```

**Comment by rsgalloway** [comment]
solution may involve sourcing exported stack (with aliases) to the subshell before running the command

**Comment by rsgalloway** [comment]
addressing this in branch [bug/1-resolve-aliases](https://github.com/rsgalloway/envstack/tree/bug/1-resolve-aliases)
